name: code_excerpt_updater
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  logging: ^1.0.1
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  mockito: ^5.0.7
  test: ^1.17.0
